name: ❤️️ Unit Testing

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - uses: actions/checkout@v3
    - name: ⚙️ Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: ⚙️ Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt --no-cache-dir
    - name: ❤️️ Test with PyTest
      run: |
        pytest
